---

env:
  es6: true
  node: true
  mocha: true
extends: eslint:recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  camelcase: 0
  comma-dangle: 0
  jsx-quotes:
    - 2
    - prefer-single
  key-spacing: 0
  new-cap:
    - 2
    - capIsNew: false
  no-console: 0
  no-extra-parens:
    - 2
    - functions
  no-multi-spaces: 0
  no-redeclare:
    - 2
    - builtinGlobals: true
  no-trailing-spaces: 0
  no-undef: 2
  no-underscore-dangle: 0
  no-unexpected-multiline: 2
  no-unreachable: 2
  no-unused-vars:
   - 2
   - vars: all
     args: none
  no-use-before-define: 0
  prefer-const: 1
  quotes:
    - 2
    - single
  semi:
    - 2
    - never
  space-before-function-paren:
    - 2
    - always
  strict: 0
  wrap-iife:
    - 2
    - inside
